site_name: Sanjay Blog
site_url: https://sanjaykmenon.github.io/sanjay-blog/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search
  - blog 
  # - social



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

# extra:
#   social:
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/sanjaykrishna
#     - icon: fontawesome/brands/github
#       link: https://github.com/sanjaykmenon

copyright: |
  &copy; 2024 <a href="https://github.com/sanjaykmenon"  target="_blank" rel="noopener">Sanjay Krishna</a>
